dependencies:
- name: elasticsearch
  version: 1.0.0
  repository: file://./charts/elasticsearch
  condition: elasticsearch-logging.enabled
- name: kibana
  version: 1.0.0
  repository: file://./charts/kibana
  condition: kibana-logging.enabled
- name: elasticsearch-curator
  version: 1.0.0
  repository: file://./charts/elasticsearch-curator
  condition: elasticsearch-curator.enabled
